services:
  - docker

script:
  - chmod +x ./build.sh
  - ./build.sh

addons:
  artifacts:
    paths:
      - builds/$(cat builds/LATEST_BUILD)
    target_paths:
      - /nginx/
    s3_region:
      - eu-west-2
